vpc_cidr        = "10.0.0.0/16"
vpc_name        = "suse-dev-vpc"
web_sg_name     = "suse-dev-web-sg"
backend_sg_name = "suse-dev-backend-sg"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"